/*
 * Copyright (C) 2014 Federico Dossena
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.dosse.bwentrain.editor;

import com.dosse.bwentrain.core.Preset;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dosse
 */
public abstract class DetailsEditPanel extends javax.swing.JPanel implements IEditable{

    private final Preset preset;

    public DetailsEditPanel(Preset p) {
        initComponents();
        preset = p;
        forceLayoutUpdate();
        title.addFocusListener(new FocusAdapter() {
            String s;

            @Override
            public void focusGained(FocusEvent e) {
                s=title.getText();
            }

            @Override
            public void focusLost(FocusEvent e) {
                if(!title.getText().equals(s)) onEdit();
            }
            
        });
        author.addFocusListener(new FocusAdapter() {
            String s;

            @Override
            public void focusGained(FocusEvent e) {
                s=author.getText();
            }

            @Override
            public void focusLost(FocusEvent e) {
                if(!author.getText().equals(s)) onEdit();
            }
            
        });
        description.addFocusListener(new FocusAdapter() {
            String s;

            @Override
            public void focusGained(FocusEvent e) {
                s=description.getText();
            }

            @Override
            public void focusLost(FocusEvent e) {
                if(!description.getText().equals(s)) onEdit();
            }
            
        });
    }

    public void forceLayoutUpdate() {
        title.setText(preset.getTitle());
        title.setCaretPosition(0);
        author.setText(preset.getAuthor());
        author.setCaretPosition(0);
        description.setText(preset.getDescription());
        description.setCaretPosition(0);
        length.setText(Utils.toHMS(preset.getLength()) + (preset.loops() ? (", " + Utils.getLocString("DETAILS_LOOPS_AFTER") + " " + Utils.toHMS(preset.getLoop())) : ""));
    }

    public abstract void lengthChangeRequested(); //called when user presses set duration within this panel

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        length = new javax.swing.JLabel();
        setLength = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/dosse/bwentrain/editor/locale"); // NOI18N
        jLabel1.setText(bundle.getString("DetailsEditPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("DetailsEditPanel.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("DetailsEditPanel.jLabel3.text")); // NOI18N

        title.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e) {
                preset.setTitle(title.getText());
            }
            public void removeUpdate(DocumentEvent e) {
                preset.setTitle(title.getText());
            }
            public void insertUpdate(DocumentEvent e) {
                preset.setTitle(title.getText());
            }
        });

        author.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e) {
                preset.setAuthor(author.getText());
            }
            public void removeUpdate(DocumentEvent e) {
                preset.setAuthor(author.getText());
            }
            public void insertUpdate(DocumentEvent e) {
                preset.setAuthor(author.getText());
            }
        });

        description.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent e) {
                preset.setDescription(description.getText());
            }
            public void removeUpdate(DocumentEvent e) {
                preset.setDescription(description.getText());
            }
            public void insertUpdate(DocumentEvent e) {
                preset.setDescription(description.getText());
            }
        });

        jLabel5.setText(bundle.getString("DetailsEditPanel.jLabel5.text")); // NOI18N

        setLength.setText(bundle.getString("DetailsEditPanel.setLength.text")); // NOI18N
        setLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLengthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(description, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setLength)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(length, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(length)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setLength)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLengthActionPerformed
        lengthChangeRequested();
    }//GEN-LAST:event_setLengthActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JTextField description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel length;
    private javax.swing.JButton setLength;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
