#!/bin/bash
#using https://github.com/Jorl17/jar2app
JDKPATH="/Library/Java/JavaVirtualMachines/"
JDKVERSION="jdk1.7.0_80.jdk"
APPNAME="SINE Editor"
BUNDLENAME="com.dosse.bwentrain.editor"
ICONNAME="iconeditor.icns"
VERSION="1.8.8"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}"

rm -fr "SINE/$APPNAME.app"

if [ $1 == "-r" ]; then
	jar2app ../../SINE-Editor/dist/SINE-Editor.jar -i $ICONNAME -r "$JDKPATH/$JDKVERSION/" -b "$BUNDLENAME" -v "$VERSION" -s "$VERSION" -o "SINE/$APPNAME.app"
	mv "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home/jre" "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/"
	rm -r "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home/"
	mkdir "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home"
	mv "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/jre" "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home/jre"
else
	jar2app ../../SINE-Editor/dist/SINE-Editor.jar -i $ICONNAME -b "$BUNDLENAME" -v "$VERSION" -s "$VERSION" -o "SINE/$APPNAME.app"
fi

mkdir "SINE/$APPNAME.app/Contents/Java/lib"
cp "../../SINE-Editor/dist/lib/"* "SINE/$APPNAME.app/Contents/Java/lib/"


