#!/bin/bash
#using https://github.com/Jorl17/jar2app
JDKPATH="/Library/Java/JavaVirtualMachines/"
JDKVERSION="jdk1.7.0_80.jdk"
APPNAME="SINE"
BUNDLENAME="com.dosse.bwentrain.player"
EXTDESC="SINE Preset"
EXT="sin"
ICONNAME="icon.icns"
VERSION="1.8.7"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}"

rm -fr "SINE/$APPNAME.app"

if [ $1 == "-r" ]; then
	jar2app ../../SINE/dist/SINE.jar -i $ICONNAME -r "$JDKPATH/$JDKVERSION" -b $BUNDLENAME -v "$VERSION" -s "$VERSION" -o "SINE/$APPNAME.app"
	mv "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home/jre" "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/"
	rm -r "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home/"
	mkdir "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home"
	mv "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/jre" "SINE/$APPNAME.app/Contents/PlugIns/$JDKVERSION/Contents/Home/"
else
	jar2app ../../SINE/dist/SINE.jar -i $ICONNAME -b $BUNDLENAME -v "$VERSION" -s "$VERSION" -o "SINE/$APPNAME.app"
fi

mkdir "SINE/$APPNAME.app/Contents/Java/lib"
cp "../../SINE/dist/lib/"* "SINE/$APPNAME.app/Contents/Java/lib/"
cp "presetIcon.icns" "SINE/$APPNAME.app/Contents/Resources/"

#add linking to .sin extension
plutil -insert CFBundleDocumentTypes -xml "<array>
    <dict>
        <key>CFBundleTypeName </key>
        <string>$EXTDESC</string>
        <key>CFBundleTypeRole</key>
        <string>Viewer</string>
        <key>LSHandlerRank</key>
        <string>Owner</string>
        <key>LSItemContentTypes</key>
        <array>
            <string>$BUNDLENAME.$EXT</string>
        </array>
	<key>CFBundleTypeIconFile</key>
	<string>presetIcon</string>
    </dict>
</array>" "SINE/$APPNAME.app/Contents/Info.plist"