#!/bin/bash
#using https://github.com/Jorl17/jar2app
APPNAME="SINE"
BUNDLENAME="com.dosse.bwentrain.player"
EXTDESC="SINE Preset"
EXT="sin"
ICONNAME="icon.icns"
VERSION="1.8.7"

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}"

rm -fr "out/$APPNAME.app"

if [ $1 == "-r" ]; then
	jar2app ../SINE/dist/SINE.jar -i $ICONNAME -r "/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/" -b $BUNDLENAME -v "$VERSION" -s "$VERSION" -o "out/$APPNAME.app"
else
	jar2app ../SINE/dist/SINE.jar -i $ICONNAME -b $BUNDLENAME -v "$VERSION" -s "$VERSION" -o "out/$APPNAME.app"
fi

mkdir "out/$APPNAME.app/Contents/Java/lib"
cp "../SINE/dist/lib/"* "out/$APPNAME.app/Contents/Java/lib/"

#add linking to .sin extension
plutil -insert CFBundleDocumentTypes -xml '<array>
	<dict>
        <key>CFBundleTypeName</key>
        <string>$EXTDESC</string>
        <key>CFBundleTypeRole</key>
        <string>Viewer</string>
        <key>LSHandlerRank</key>
        <string>Owner</string>
        <key>LSItemContentTypes</key>
        <array>
            <string>$BUNDLENAME.$EXT</string>
        </array>
    </dict>
</array>' $APPNAME.app/Contents/Info.plist



plutil -insert UTExportedTypeDeclarations -xml '<array>
<dict>
        <key>UTTypeConformsTo</key>
        <array>
            <string>public.data</string>
        </array>
        <key>UTTypeDescription</key>
        <string>$EXTDESC</string>
        <key>UTTypeIdentifier</key>
        <string>$BUNDLENAME.$EXT</string>
        <key>UTTypeTagSpecification</key>
        <dict>
            <key>public.filename-extension</key>
            <string>$EXT</string>
            <key>public.mime-type</key>
            <string>application/xml</string>
        </dict>
    </dict>
</array>' $APPNAME.app/Contents/Info.plist



